<?php

use Illuminate\Database\Seeder;
use App\Kota;

class KotaTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Kota::create(['id' => 1101 , 'prov_id' => '11' , 'name' => 'KABUPATEN SIMEULUE',]);
        Kota::create(['id' => 1102 , 'prov_id' => '11' , 'name' => 'KABUPATEN ACEH SINGKIL',]);
        Kota::create(['id' => 1103 , 'prov_id' => '11' , 'name' => 'KABUPATEN ACEH SELATAN',]);
        Kota::create(['id' => 1104 , 'prov_id' => '11' , 'name' => 'KABUPATEN ACEH TENGGARA',]);
        Kota::create(['id' => 1105 , 'prov_id' => '11' , 'name' => 'KABUPATEN ACEH TIMUR',]);
        Kota::create(['id' => 1106 , 'prov_id' => '11' , 'name' => 'KABUPATEN ACEH TENGAH',]);
        Kota::create(['id' => 1107 , 'prov_id' => '11' , 'name' => 'KABUPATEN ACEH BARAT',]);
        Kota::create(['id' => 1108 , 'prov_id' => '11' , 'name' => 'KABUPATEN ACEH BESAR',]);
        Kota::create(['id' => 1109 , 'prov_id' => '11' , 'name' => 'KABUPATEN PIDIE',]);
        Kota::create(['id' => 1110 , 'prov_id' => '11' , 'name' => 'KABUPATEN BIREUEN',]);
        Kota::create(['id' => 1111 , 'prov_id' => '11' , 'name' => 'KABUPATEN ACEH UTARA',]);
        Kota::create(['id' => 1112 , 'prov_id' => '11' , 'name' => 'KABUPATEN ACEH BARAT DAYA',]);
        Kota::create(['id' => 1113 , 'prov_id' => '11' , 'name' => 'KABUPATEN GAYO LUES',]);
        Kota::create(['id' => 1114 , 'prov_id' => '11' , 'name' => 'KABUPATEN ACEH TAMIANG',]);
        Kota::create(['id' => 1115 , 'prov_id' => '11' , 'name' => 'KABUPATEN NAGAN RAYA',]);
        Kota::create(['id' => 1116 , 'prov_id' => '11' , 'name' => 'KABUPATEN ACEH JAYA',]);
        Kota::create(['id' => 1117 , 'prov_id' => '11' , 'name' => 'KABUPATEN BENER MERIAH',]);
        Kota::create(['id' => 1118 , 'prov_id' => '11' , 'name' => 'KABUPATEN PIDIE JAYA',]);
        Kota::create(['id' => 1171 , 'prov_id' => '11' , 'name' => 'KOTA BANDA ACEH',]);
        Kota::create(['id' => 1172 , 'prov_id' => '11' , 'name' => 'KOTA SABANG',]);
        Kota::create(['id' => 1173 , 'prov_id' => '11' , 'name' => 'KOTA LANGSA',]);
        Kota::create(['id' => 1174 , 'prov_id' => '11' , 'name' => 'KOTA LHOKSEUMAWE',]);
        Kota::create(['id' => 1175 , 'prov_id' => '11' , 'name' => 'KOTA SUBULUSSALAM',]);
        Kota::create(['id' => 1201 , 'prov_id' => '12' , 'name' => 'KABUPATEN NIAS',]);
        Kota::create(['id' => 1202 , 'prov_id' => '12' , 'name' => 'KABUPATEN MANDAILING NATAL',]);
        Kota::create(['id' => 1203 , 'prov_id' => '12' , 'name' => 'KABUPATEN TAPANULI SELATAN',]);
        Kota::create(['id' => 1204 , 'prov_id' => '12' , 'name' => 'KABUPATEN TAPANULI TENGAH',]);
        Kota::create(['id' => 1205 , 'prov_id' => '12' , 'name' => 'KABUPATEN TAPANULI UTARA',]);
        Kota::create(['id' => 1206 , 'prov_id' => '12' , 'name' => 'KABUPATEN TOBA SAMOSIR',]);
        Kota::create(['id' => 1207 , 'prov_id' => '12' , 'name' => 'KABUPATEN LABUHAN BATU',]);
        Kota::create(['id' => 1208 , 'prov_id' => '12' , 'name' => 'KABUPATEN ASAHAN',]);
        Kota::create(['id' => 1209 , 'prov_id' => '12' , 'name' => 'KABUPATEN SIMALUNGUN',]);
        Kota::create(['id' => 1210 , 'prov_id' => '12' , 'name' => 'KABUPATEN DAIRI',]);
        Kota::create(['id' => 1211 , 'prov_id' => '12' , 'name' => 'KABUPATEN KARO',]);
        Kota::create(['id' => 1212 , 'prov_id' => '12' , 'name' => 'KABUPATEN DELI SERDANG',]);
        Kota::create(['id' => 1213 , 'prov_id' => '12' , 'name' => 'KABUPATEN LANGKAT',]);
        Kota::create(['id' => 1214 , 'prov_id' => '12' , 'name' => 'KABUPATEN NIAS SELATAN',]);
        Kota::create(['id' => 1215 , 'prov_id' => '12' , 'name' => 'KABUPATEN HUMBANG HASUNDUTAN',]);
        Kota::create(['id' => 1216 , 'prov_id' => '12' , 'name' => 'KABUPATEN PAKPAK BHARAT',]);
        Kota::create(['id' => 1217 , 'prov_id' => '12' , 'name' => 'KABUPATEN SAMOSIR',]);
        Kota::create(['id' => 1218 , 'prov_id' => '12' , 'name' => 'KABUPATEN SERDANG BEDAGAI',]);
        Kota::create(['id' => 1219 , 'prov_id' => '12' , 'name' => 'KABUPATEN BATU BARA',]);
        Kota::create(['id' => 1220 , 'prov_id' => '12' , 'name' => 'KABUPATEN PADANG LAWAS UTARA',]);
        Kota::create(['id' => 1221 , 'prov_id' => '12' , 'name' => 'KABUPATEN PADANG LAWAS',]);
        Kota::create(['id' => 1222 , 'prov_id' => '12' , 'name' => 'KABUPATEN LABUHAN BATU SELATAN',]);
        Kota::create(['id' => 1223 , 'prov_id' => '12' , 'name' => 'KABUPATEN LABUHAN BATU UTARA',]);
        Kota::create(['id' => 1224 , 'prov_id' => '12' , 'name' => 'KABUPATEN NIAS UTARA',]);
        Kota::create(['id' => 1225 , 'prov_id' => '12' , 'name' => 'KABUPATEN NIAS BARAT',]);
        Kota::create(['id' => 1271 , 'prov_id' => '12' , 'name' => 'KOTA SIBOLGA',]);
        Kota::create(['id' => 1272 , 'prov_id' => '12' , 'name' => 'KOTA TANJUNG BALAI',]);
        Kota::create(['id' => 1273 , 'prov_id' => '12' , 'name' => 'KOTA PEMATANG SIANTAR',]);
        Kota::create(['id' => 1274 , 'prov_id' => '12' , 'name' => 'KOTA TEBING TINGGI',]);
        Kota::create(['id' => 1275 , 'prov_id' => '12' , 'name' => 'KOTA MEDAN',]);
        Kota::create(['id' => 1276 , 'prov_id' => '12' , 'name' => 'KOTA BINJAI',]);
        Kota::create(['id' => 1277 , 'prov_id' => '12' , 'name' => 'KOTA PADANGSIDIMPUAN',]);
        Kota::create(['id' => 1278 , 'prov_id' => '12' , 'name' => 'KOTA GUNUNGSITOLI',]);
        Kota::create(['id' => 1301 , 'prov_id' => '13' , 'name' => 'KABUPATEN KEPULAUAN MENTAWAI',]);
        Kota::create(['id' => 1302 , 'prov_id' => '13' , 'name' => 'KABUPATEN PESISIR SELATAN',]);
        Kota::create(['id' => 1303 , 'prov_id' => '13' , 'name' => 'KABUPATEN SOLOK',]);
        Kota::create(['id' => 1304 , 'prov_id' => '13' , 'name' => 'KABUPATEN SIJUNJUNG',]);
        Kota::create(['id' => 1305 , 'prov_id' => '13' , 'name' => 'KABUPATEN TANAH DATAR',]);
        Kota::create(['id' => 1306 , 'prov_id' => '13' , 'name' => 'KABUPATEN PADANG PARIAMAN',]);
        Kota::create(['id' => 1307 , 'prov_id' => '13' , 'name' => 'KABUPATEN AGAM',]);
        Kota::create(['id' => 1308 , 'prov_id' => '13' , 'name' => 'KABUPATEN LIMA PULUH KOTA',]);
        Kota::create(['id' => 1309 , 'prov_id' => '13' , 'name' => 'KABUPATEN PASAMAN',]);
        Kota::create(['id' => 1310 , 'prov_id' => '13' , 'name' => 'KABUPATEN SOLOK SELATAN',]);
        Kota::create(['id' => 1311 , 'prov_id' => '13' , 'name' => 'KABUPATEN DHARMASRAYA',]);
        Kota::create(['id' => 1312 , 'prov_id' => '13' , 'name' => 'KABUPATEN PASAMAN BARAT',]);
        Kota::create(['id' => 1371 , 'prov_id' => '13' , 'name' => 'KOTA PADANG',]);
        Kota::create(['id' => 1372 , 'prov_id' => '13' , 'name' => 'KOTA SOLOK',]);
        Kota::create(['id' => 1373 , 'prov_id' => '13' , 'name' => 'KOTA SAWAH LUNTO',]);
        Kota::create(['id' => 1374 , 'prov_id' => '13' , 'name' => 'KOTA PADANG PANJANG',]);
        Kota::create(['id' => 1375 , 'prov_id' => '13' , 'name' => 'KOTA BUKITTINGGI',]);
        Kota::create(['id' => 1376 , 'prov_id' => '13' , 'name' => 'KOTA PAYAKUMBUH',]);
        Kota::create(['id' => 1377 , 'prov_id' => '13' , 'name' => 'KOTA PARIAMAN',]);
        Kota::create(['id' => 1401 , 'prov_id' => '14' , 'name' => 'KABUPATEN KUANTAN SINGINGI',]);
        Kota::create(['id' => 1402 , 'prov_id' => '14' , 'name' => 'KABUPATEN INDRAGIRI HULU',]);
        Kota::create(['id' => 1403 , 'prov_id' => '14' , 'name' => 'KABUPATEN INDRAGIRI HILIR',]);
        Kota::create(['id' => 1404 , 'prov_id' => '14' , 'name' => 'KABUPATEN PELALAWAN',]);
        Kota::create(['id' => 1405 , 'prov_id' => '14' , 'name' => 'KABUPATEN S I A K',]);
        Kota::create(['id' => 1406 , 'prov_id' => '14' , 'name' => 'KABUPATEN KAMPAR',]);
        Kota::create(['id' => 1407 , 'prov_id' => '14' , 'name' => 'KABUPATEN ROKAN HULU',]);
        Kota::create(['id' => 1408 , 'prov_id' => '14' , 'name' => 'KABUPATEN BENGKALIS',]);
        Kota::create(['id' => 1409 , 'prov_id' => '14' , 'name' => 'KABUPATEN ROKAN HILIR',]);
        Kota::create(['id' => 1410 , 'prov_id' => '14' , 'name' => 'KABUPATEN KEPULAUAN MERANTI',]);
        Kota::create(['id' => 1471 , 'prov_id' => '14' , 'name' => 'KOTA PEKANBARU',]);
        Kota::create(['id' => 1473 , 'prov_id' => '14' , 'name' => 'KOTA D U M A I',]);
        Kota::create(['id' => 1501 , 'prov_id' => '15' , 'name' => 'KABUPATEN KERINCI',]);
        Kota::create(['id' => 1502 , 'prov_id' => '15' , 'name' => 'KABUPATEN MERANGIN',]);
        Kota::create(['id' => 1503 , 'prov_id' => '15' , 'name' => 'KABUPATEN SAROLANGUN',]);
        Kota::create(['id' => 1504 , 'prov_id' => '15' , 'name' => 'KABUPATEN BATANG HARI',]);
        Kota::create(['id' => 1505 , 'prov_id' => '15' , 'name' => 'KABUPATEN MUARO JAMBI',]);
        Kota::create(['id' => 1506 , 'prov_id' => '15' , 'name' => 'KABUPATEN TANJUNG JABUNG TIMUR',]);
        Kota::create(['id' => 1507 , 'prov_id' => '15' , 'name' => 'KABUPATEN TANJUNG JABUNG BARAT',]);
        Kota::create(['id' => 1508 , 'prov_id' => '15' , 'name' => 'KABUPATEN TEBO',]);
        Kota::create(['id' => 1509 , 'prov_id' => '15' , 'name' => 'KABUPATEN BUNGO',]);
        Kota::create(['id' => 1571 , 'prov_id' => '15' , 'name' => 'KOTA JAMBI',]);
        Kota::create(['id' => 1572 , 'prov_id' => '15' , 'name' => 'KOTA SUNGAI PENUH',]);
        Kota::create(['id' => 1601 , 'prov_id' => '16' , 'name' => 'KABUPATEN OGAN KOMERING ULU',]);
        Kota::create(['id' => 1602 , 'prov_id' => '16' , 'name' => 'KABUPATEN OGAN KOMERING ILIR',]);
        Kota::create(['id' => 1603 , 'prov_id' => '16' , 'name' => 'KABUPATEN MUARA ENIM',]);
        Kota::create(['id' => 1604 , 'prov_id' => '16' , 'name' => 'KABUPATEN LAHAT',]);
        Kota::create(['id' => 1605 , 'prov_id' => '16' , 'name' => 'KABUPATEN MUSI RAWAS',]);
        Kota::create(['id' => 1606 , 'prov_id' => '16' , 'name' => 'KABUPATEN MUSI BANYUASIN',]);
        Kota::create(['id' => 1607 , 'prov_id' => '16' , 'name' => 'KABUPATEN BANYU ASIN',]);
        Kota::create(['id' => 1608 , 'prov_id' => '16' , 'name' => 'KABUPATEN OGAN KOMERING ULU SELATAN',]);
        Kota::create(['id' => 1609 , 'prov_id' => '16' , 'name' => 'KABUPATEN OGAN KOMERING ULU TIMUR',]);
        Kota::create(['id' => 1610 , 'prov_id' => '16' , 'name' => 'KABUPATEN OGAN ILIR',]);
        Kota::create(['id' => 1611 , 'prov_id' => '16' , 'name' => 'KABUPATEN EMPAT LAWANG',]);
        Kota::create(['id' => 1612 , 'prov_id' => '16' , 'name' => 'KABUPATEN PENUKAL ABAB LEMATANG ILIR',]);
        Kota::create(['id' => 1613 , 'prov_id' => '16' , 'name' => 'KABUPATEN MUSI RAWAS UTARA',]);
        Kota::create(['id' => 1671 , 'prov_id' => '16' , 'name' => 'KOTA PALEMBANG',]);
        Kota::create(['id' => 1672 , 'prov_id' => '16' , 'name' => 'KOTA PRABUMULIH',]);
        Kota::create(['id' => 1673 , 'prov_id' => '16' , 'name' => 'KOTA PAGAR ALAM',]);
        Kota::create(['id' => 1674 , 'prov_id' => '16' , 'name' => 'KOTA LUBUKLINGGAU',]);
        Kota::create(['id' => 1701 , 'prov_id' => '17' , 'name' => 'KABUPATEN BENGKULU SELATAN',]);
        Kota::create(['id' => 1702 , 'prov_id' => '17' , 'name' => 'KABUPATEN REJANG LEBONG',]);
        Kota::create(['id' => 1703 , 'prov_id' => '17' , 'name' => 'KABUPATEN BENGKULU UTARA',]);
        Kota::create(['id' => 1704 , 'prov_id' => '17' , 'name' => 'KABUPATEN KAUR',]);
        Kota::create(['id' => 1705 , 'prov_id' => '17' , 'name' => 'KABUPATEN SELUMA',]);
        Kota::create(['id' => 1706 , 'prov_id' => '17' , 'name' => 'KABUPATEN MUKOMUKO',]);
        Kota::create(['id' => 1707 , 'prov_id' => '17' , 'name' => 'KABUPATEN LEBONG',]);
        Kota::create(['id' => 1708 , 'prov_id' => '17' , 'name' => 'KABUPATEN KEPAHIANG',]);
        Kota::create(['id' => 1709 , 'prov_id' => '17' , 'name' => 'KABUPATEN BENGKULU TENGAH',]);
        Kota::create(['id' => 1771 , 'prov_id' => '17' , 'name' => 'KOTA BENGKULU',]);
        Kota::create(['id' => 1801 , 'prov_id' => '18' , 'name' => 'KABUPATEN LAMPUNG BARAT',]);
        Kota::create(['id' => 1802 , 'prov_id' => '18' , 'name' => 'KABUPATEN TANGGAMUS',]);
        Kota::create(['id' => 1803 , 'prov_id' => '18' , 'name' => 'KABUPATEN LAMPUNG SELATAN',]);
        Kota::create(['id' => 1804 , 'prov_id' => '18' , 'name' => 'KABUPATEN LAMPUNG TIMUR',]);
        Kota::create(['id' => 1805 , 'prov_id' => '18' , 'name' => 'KABUPATEN LAMPUNG TENGAH',]);
        Kota::create(['id' => 1806 , 'prov_id' => '18' , 'name' => 'KABUPATEN LAMPUNG UTARA',]);
        Kota::create(['id' => 1807 , 'prov_id' => '18' , 'name' => 'KABUPATEN WAY KANAN',]);
        Kota::create(['id' => 1808 , 'prov_id' => '18' , 'name' => 'KABUPATEN TULANGBAWANG',]);
        Kota::create(['id' => 1809 , 'prov_id' => '18' , 'name' => 'KABUPATEN PESAWARAN',]);
        Kota::create(['id' => 1810 , 'prov_id' => '18' , 'name' => 'KABUPATEN PRINGSEWU',]);
        Kota::create(['id' => 1811 , 'prov_id' => '18' , 'name' => 'KABUPATEN MESUJI',]);
        Kota::create(['id' => 1812 , 'prov_id' => '18' , 'name' => 'KABUPATEN TULANG BAWANG BARAT',]);
        Kota::create(['id' => 1813 , 'prov_id' => '18' , 'name' => 'KABUPATEN PESISIR BARAT',]);
        Kota::create(['id' => 1871 , 'prov_id' => '18' , 'name' => 'KOTA BANDAR LAMPUNG',]);
        Kota::create(['id' => 1872 , 'prov_id' => '18' , 'name' => 'KOTA METRO',]);
        Kota::create(['id' => 1901 , 'prov_id' => '19' , 'name' => 'KABUPATEN BANGKA',]);
        Kota::create(['id' => 1902 , 'prov_id' => '19' , 'name' => 'KABUPATEN BELITUNG',]);
        Kota::create(['id' => 1903 , 'prov_id' => '19' , 'name' => 'KABUPATEN BANGKA BARAT',]);
        Kota::create(['id' => 1904 , 'prov_id' => '19' , 'name' => 'KABUPATEN BANGKA TENGAH',]);
        Kota::create(['id' => 1905 , 'prov_id' => '19' , 'name' => 'KABUPATEN BANGKA SELATAN',]);
        Kota::create(['id' => 1906 , 'prov_id' => '19' , 'name' => 'KABUPATEN BELITUNG TIMUR',]);
        Kota::create(['id' => 1971 , 'prov_id' => '19' , 'name' => 'KOTA PANGKAL PINANG',]);
        Kota::create(['id' => 2101 , 'prov_id' => '21' , 'name' => 'KABUPATEN KARIMUN',]);
        Kota::create(['id' => 2102 , 'prov_id' => '21' , 'name' => 'KABUPATEN BINTAN',]);
        Kota::create(['id' => 2103 , 'prov_id' => '21' , 'name' => 'KABUPATEN NATUNA',]);
        Kota::create(['id' => 2104 , 'prov_id' => '21' , 'name' => 'KABUPATEN LINGGA',]);
        Kota::create(['id' => 2105 , 'prov_id' => '21' , 'name' => 'KABUPATEN KEPULAUAN ANAMBAS',]);
        Kota::create(['id' => 2171 , 'prov_id' => '21' , 'name' => 'KOTA B A T A M',]);
        Kota::create(['id' => 2172 , 'prov_id' => '21' , 'name' => 'KOTA TANJUNG PINANG',]);
        Kota::create(['id' => 3101 , 'prov_id' => '31' , 'name' => 'KABUPATEN KEPULAUAN SERIBU',]);
        Kota::create(['id' => 3171 , 'prov_id' => '31' , 'name' => 'KOTA JAKARTA SELATAN',]);
        Kota::create(['id' => 3172 , 'prov_id' => '31' , 'name' => 'KOTA JAKARTA TIMUR',]);
        Kota::create(['id' => 3173 , 'prov_id' => '31' , 'name' => 'KOTA JAKARTA PUSAT',]);
        Kota::create(['id' => 3174 , 'prov_id' => '31' , 'name' => 'KOTA JAKARTA BARAT',]);
        Kota::create(['id' => 3175 , 'prov_id' => '31' , 'name' => 'KOTA JAKARTA UTARA',]);
        Kota::create(['id' => 3201 , 'prov_id' => '32' , 'name' => 'KABUPATEN BOGOR',]);
        Kota::create(['id' => 3202 , 'prov_id' => '32' , 'name' => 'KABUPATEN SUKABUMI',]);
        Kota::create(['id' => 3203 , 'prov_id' => '32' , 'name' => 'KABUPATEN CIANJUR',]);
        Kota::create(['id' => 3204 , 'prov_id' => '32' , 'name' => 'KABUPATEN BANDUNG',]);
        Kota::create(['id' => 3205 , 'prov_id' => '32' , 'name' => 'KABUPATEN GARUT',]);
        Kota::create(['id' => 3206 , 'prov_id' => '32' , 'name' => 'KABUPATEN TASIKMALAYA',]);
        Kota::create(['id' => 3207 , 'prov_id' => '32' , 'name' => 'KABUPATEN CIAMIS',]);
        Kota::create(['id' => 3208 , 'prov_id' => '32' , 'name' => 'KABUPATEN KUNINGAN',]);
        Kota::create(['id' => 3209 , 'prov_id' => '32' , 'name' => 'KABUPATEN CIREBON',]);
        Kota::create(['id' => 3210 , 'prov_id' => '32' , 'name' => 'KABUPATEN MAJALENGKA',]);
        Kota::create(['id' => 3211 , 'prov_id' => '32' , 'name' => 'KABUPATEN SUMEDANG',]);
        Kota::create(['id' => 3212 , 'prov_id' => '32' , 'name' => 'KABUPATEN INDRAMAYU',]);
        Kota::create(['id' => 3213 , 'prov_id' => '32' , 'name' => 'KABUPATEN SUBANG',]);
        Kota::create(['id' => 3214 , 'prov_id' => '32' , 'name' => 'KABUPATEN PURWAKARTA',]);
        Kota::create(['id' => 3215 , 'prov_id' => '32' , 'name' => 'KABUPATEN KARAWANG',]);
        Kota::create(['id' => 3216 , 'prov_id' => '32' , 'name' => 'KABUPATEN BEKASI',]);
        Kota::create(['id' => 3217 , 'prov_id' => '32' , 'name' => 'KABUPATEN BANDUNG BARAT',]);
        Kota::create(['id' => 3218 , 'prov_id' => '32' , 'name' => 'KABUPATEN PANGANDARAN',]);
        Kota::create(['id' => 3271 , 'prov_id' => '32' , 'name' => 'KOTA BOGOR',]);
        Kota::create(['id' => 3272 , 'prov_id' => '32' , 'name' => 'KOTA SUKABUMI',]);
        Kota::create(['id' => 3273 , 'prov_id' => '32' , 'name' => 'KOTA BANDUNG',]);
        Kota::create(['id' => 3274 , 'prov_id' => '32' , 'name' => 'KOTA CIREBON',]);
        Kota::create(['id' => 3275 , 'prov_id' => '32' , 'name' => 'KOTA BEKASI',]);
        Kota::create(['id' => 3276 , 'prov_id' => '32' , 'name' => 'KOTA DEPOK',]);
        Kota::create(['id' => 3277 , 'prov_id' => '32' , 'name' => 'KOTA CIMAHI',]);
        Kota::create(['id' => 3278 , 'prov_id' => '32' , 'name' => 'KOTA TASIKMALAYA',]);
        Kota::create(['id' => 3279 , 'prov_id' => '32' , 'name' => 'KOTA BANJAR',]);
        Kota::create(['id' => 3301 , 'prov_id' => '33' , 'name' => 'KABUPATEN CILACAP',]);
        Kota::create(['id' => 3302 , 'prov_id' => '33' , 'name' => 'KABUPATEN BANYUMAS',]);
        Kota::create(['id' => 3303 , 'prov_id' => '33' , 'name' => 'KABUPATEN PURBALINGGA',]);
        Kota::create(['id' => 3304 , 'prov_id' => '33' , 'name' => 'KABUPATEN BANJARNEGARA',]);
        Kota::create(['id' => 3305 , 'prov_id' => '33' , 'name' => 'KABUPATEN KEBUMEN',]);
        Kota::create(['id' => 3306 , 'prov_id' => '33' , 'name' => 'KABUPATEN PURWOREJO',]);
        Kota::create(['id' => 3307 , 'prov_id' => '33' , 'name' => 'KABUPATEN WONOSOBO',]);
        Kota::create(['id' => 3308 , 'prov_id' => '33' , 'name' => 'KABUPATEN MAGELANG',]);
        Kota::create(['id' => 3309 , 'prov_id' => '33' , 'name' => 'KABUPATEN BOYOLALI',]);
        Kota::create(['id' => 3310 , 'prov_id' => '33' , 'name' => 'KABUPATEN KLATEN',]);
        Kota::create(['id' => 3311 , 'prov_id' => '33' , 'name' => 'KABUPATEN SUKOHARJO',]);
        Kota::create(['id' => 3312 , 'prov_id' => '33' , 'name' => 'KABUPATEN WONOGIRI',]);
        Kota::create(['id' => 3313 , 'prov_id' => '33' , 'name' => 'KABUPATEN KARANGANYAR',]);
        Kota::create(['id' => 3314 , 'prov_id' => '33' , 'name' => 'KABUPATEN SRAGEN',]);
        Kota::create(['id' => 3315 , 'prov_id' => '33' , 'name' => 'KABUPATEN GROBOGAN',]);
        Kota::create(['id' => 3316 , 'prov_id' => '33' , 'name' => 'KABUPATEN BLORA',]);
        Kota::create(['id' => 3317 , 'prov_id' => '33' , 'name' => 'KABUPATEN REMBANG',]);
        Kota::create(['id' => 3318 , 'prov_id' => '33' , 'name' => 'KABUPATEN PATI',]);
        Kota::create(['id' => 3319 , 'prov_id' => '33' , 'name' => 'KABUPATEN KUDUS',]);
        Kota::create(['id' => 3320 , 'prov_id' => '33' , 'name' => 'KABUPATEN JEPARA',]);
        Kota::create(['id' => 3321 , 'prov_id' => '33' , 'name' => 'KABUPATEN DEMAK',]);
        Kota::create(['id' => 3322 , 'prov_id' => '33' , 'name' => 'KABUPATEN SEMARANG',]);
        Kota::create(['id' => 3323 , 'prov_id' => '33' , 'name' => 'KABUPATEN TEMANGGUNG',]);
        Kota::create(['id' => 3324 , 'prov_id' => '33' , 'name' => 'KABUPATEN KENDAL',]);
        Kota::create(['id' => 3325 , 'prov_id' => '33' , 'name' => 'KABUPATEN BATANG',]);
        Kota::create(['id' => 3326 , 'prov_id' => '33' , 'name' => 'KABUPATEN PEKALONGAN',]);
        Kota::create(['id' => 3327 , 'prov_id' => '33' , 'name' => 'KABUPATEN PEMALANG',]);
        Kota::create(['id' => 3328 , 'prov_id' => '33' , 'name' => 'KABUPATEN TEGAL',]);
        Kota::create(['id' => 3329 , 'prov_id' => '33' , 'name' => 'KABUPATEN BREBES',]);
        Kota::create(['id' => 3371 , 'prov_id' => '33' , 'name' => 'KOTA MAGELANG',]);
        Kota::create(['id' => 3372 , 'prov_id' => '33' , 'name' => 'KOTA SURAKARTA',]);
        Kota::create(['id' => 3373 , 'prov_id' => '33' , 'name' => 'KOTA SALATIGA',]);
        Kota::create(['id' => 3374 , 'prov_id' => '33' , 'name' => 'KOTA SEMARANG',]);
        Kota::create(['id' => 3375 , 'prov_id' => '33' , 'name' => 'KOTA PEKALONGAN',]);
        Kota::create(['id' => 3376 , 'prov_id' => '33' , 'name' => 'KOTA TEGAL',]);
        Kota::create(['id' => 3401 , 'prov_id' => '34' , 'name' => 'KABUPATEN KULON PROGO',]);
        Kota::create(['id' => 3402 , 'prov_id' => '34' , 'name' => 'KABUPATEN BANTUL',]);
        Kota::create(['id' => 3403 , 'prov_id' => '34' , 'name' => 'KABUPATEN GUNUNG KIDUL',]);
        Kota::create(['id' => 3404 , 'prov_id' => '34' , 'name' => 'KABUPATEN SLEMAN',]);
        Kota::create(['id' => 3471 , 'prov_id' => '34' , 'name' => 'KOTA YOGYAKARTA',]);
        Kota::create(['id' => 3501 , 'prov_id' => '35' , 'name' => 'KABUPATEN PACITAN',]);
        Kota::create(['id' => 3502 , 'prov_id' => '35' , 'name' => 'KABUPATEN PONOROGO',]);
        Kota::create(['id' => 3503 , 'prov_id' => '35' , 'name' => 'KABUPATEN TRENGGALEK',]);
        Kota::create(['id' => 3504 , 'prov_id' => '35' , 'name' => 'KABUPATEN TULUNGAGUNG',]);
        Kota::create(['id' => 3505 , 'prov_id' => '35' , 'name' => 'KABUPATEN BLITAR',]);
        Kota::create(['id' => 3506 , 'prov_id' => '35' , 'name' => 'KABUPATEN KEDIRI',]);
        Kota::create(['id' => 3507 , 'prov_id' => '35' , 'name' => 'KABUPATEN MALANG',]);
        Kota::create(['id' => 3508 , 'prov_id' => '35' , 'name' => 'KABUPATEN LUMAJANG',]);
        Kota::create(['id' => 3509 , 'prov_id' => '35' , 'name' => 'KABUPATEN JEMBER',]);
        Kota::create(['id' => 3510 , 'prov_id' => '35' , 'name' => 'KABUPATEN BANYUWANGI',]);
        Kota::create(['id' => 3511 , 'prov_id' => '35' , 'name' => 'KABUPATEN BONDOWOSO',]);
        Kota::create(['id' => 3512 , 'prov_id' => '35' , 'name' => 'KABUPATEN SITUBONDO',]);
        Kota::create(['id' => 3513 , 'prov_id' => '35' , 'name' => 'KABUPATEN PROBOLINGGO',]);
        Kota::create(['id' => 3514 , 'prov_id' => '35' , 'name' => 'KABUPATEN PASURUAN',]);
        Kota::create(['id' => 3515 , 'prov_id' => '35' , 'name' => 'KABUPATEN SIDOARJO',]);
        Kota::create(['id' => 3516 , 'prov_id' => '35' , 'name' => 'KABUPATEN MOJOKERTO',]);
        Kota::create(['id' => 3517 , 'prov_id' => '35' , 'name' => 'KABUPATEN JOMBANG',]);
        Kota::create(['id' => 3518 , 'prov_id' => '35' , 'name' => 'KABUPATEN NGANJUK',]);
        Kota::create(['id' => 3519 , 'prov_id' => '35' , 'name' => 'KABUPATEN MADIUN',]);
        Kota::create(['id' => 3520 , 'prov_id' => '35' , 'name' => 'KABUPATEN MAGETAN',]);
        Kota::create(['id' => 3521 , 'prov_id' => '35' , 'name' => 'KABUPATEN NGAWI',]);
        Kota::create(['id' => 3522 , 'prov_id' => '35' , 'name' => 'KABUPATEN BOJONEGORO',]);
        Kota::create(['id' => 3523 , 'prov_id' => '35' , 'name' => 'KABUPATEN TUBAN',]);
        Kota::create(['id' => 3524 , 'prov_id' => '35' , 'name' => 'KABUPATEN LAMONGAN',]);
        Kota::create(['id' => 3525 , 'prov_id' => '35' , 'name' => 'KABUPATEN GRESIK',]);
        Kota::create(['id' => 3526 , 'prov_id' => '35' , 'name' => 'KABUPATEN BANGKALAN',]);
        Kota::create(['id' => 3527 , 'prov_id' => '35' , 'name' => 'KABUPATEN SAMPANG',]);
        Kota::create(['id' => 3528 , 'prov_id' => '35' , 'name' => 'KABUPATEN PAMEKASAN',]);
        Kota::create(['id' => 3529 , 'prov_id' => '35' , 'name' => 'KABUPATEN SUMENEP',]);
        Kota::create(['id' => 3571 , 'prov_id' => '35' , 'name' => 'KOTA KEDIRI',]);
        Kota::create(['id' => 3572 , 'prov_id' => '35' , 'name' => 'KOTA BLITAR',]);
        Kota::create(['id' => 3573 , 'prov_id' => '35' , 'name' => 'KOTA MALANG',]);
        Kota::create(['id' => 3574 , 'prov_id' => '35' , 'name' => 'KOTA PROBOLINGGO',]);
        Kota::create(['id' => 3575 , 'prov_id' => '35' , 'name' => 'KOTA PASURUAN',]);
        Kota::create(['id' => 3576 , 'prov_id' => '35' , 'name' => 'KOTA MOJOKERTO',]);
        Kota::create(['id' => 3577 , 'prov_id' => '35' , 'name' => 'KOTA MADIUN',]);
        Kota::create(['id' => 3578 , 'prov_id' => '35' , 'name' => 'KOTA SURABAYA',]);
        Kota::create(['id' => 3579 , 'prov_id' => '35' , 'name' => 'KOTA BATU',]);
        Kota::create(['id' => 3601 , 'prov_id' => '36' , 'name' => 'KABUPATEN PANDEGLANG',]);
        Kota::create(['id' => 3602 , 'prov_id' => '36' , 'name' => 'KABUPATEN LEBAK',]);
        Kota::create(['id' => 3603 , 'prov_id' => '36' , 'name' => 'KABUPATEN TANGERANG',]);
        Kota::create(['id' => 3604 , 'prov_id' => '36' , 'name' => 'KABUPATEN SERANG',]);
        Kota::create(['id' => 3671 , 'prov_id' => '36' , 'name' => 'KOTA TANGERANG',]);
        Kota::create(['id' => 3672 , 'prov_id' => '36' , 'name' => 'KOTA CILEGON',]);
        Kota::create(['id' => 3673 , 'prov_id' => '36' , 'name' => 'KOTA SERANG',]);
        Kota::create(['id' => 3674 , 'prov_id' => '36' , 'name' => 'KOTA TANGERANG SELATAN',]);
        Kota::create(['id' => 5101 , 'prov_id' => '51' , 'name' => 'KABUPATEN JEMBRANA',]);
        Kota::create(['id' => 5102 , 'prov_id' => '51' , 'name' => 'KABUPATEN TABANAN',]);
        Kota::create(['id' => 5103 , 'prov_id' => '51' , 'name' => 'KABUPATEN BADUNG',]);
        Kota::create(['id' => 5104 , 'prov_id' => '51' , 'name' => 'KABUPATEN GIANYAR',]);
        Kota::create(['id' => 5105 , 'prov_id' => '51' , 'name' => 'KABUPATEN KLUNGKUNG',]);
        Kota::create(['id' => 5106 , 'prov_id' => '51' , 'name' => 'KABUPATEN BANGLI',]);
        Kota::create(['id' => 5107 , 'prov_id' => '51' , 'name' => 'KABUPATEN KARANG ASEM',]);
        Kota::create(['id' => 5108 , 'prov_id' => '51' , 'name' => 'KABUPATEN BULELENG',]);
        Kota::create(['id' => 5171 , 'prov_id' => '51' , 'name' => 'KOTA DENPASAR',]);
        Kota::create(['id' => 5201 , 'prov_id' => '52' , 'name' => 'KABUPATEN LOMBOK BARAT',]);
        Kota::create(['id' => 5202 , 'prov_id' => '52' , 'name' => 'KABUPATEN LOMBOK TENGAH',]);
        Kota::create(['id' => 5203 , 'prov_id' => '52' , 'name' => 'KABUPATEN LOMBOK TIMUR',]);
        Kota::create(['id' => 5204 , 'prov_id' => '52' , 'name' => 'KABUPATEN SUMBAWA',]);
        Kota::create(['id' => 5205 , 'prov_id' => '52' , 'name' => 'KABUPATEN DOMPU',]);
        Kota::create(['id' => 5206 , 'prov_id' => '52' , 'name' => 'KABUPATEN BIMA',]);
        Kota::create(['id' => 5207 , 'prov_id' => '52' , 'name' => 'KABUPATEN SUMBAWA BARAT',]);
        Kota::create(['id' => 5208 , 'prov_id' => '52' , 'name' => 'KABUPATEN LOMBOK UTARA',]);
        Kota::create(['id' => 5271 , 'prov_id' => '52' , 'name' => 'KOTA MATARAM',]);
        Kota::create(['id' => 5272 , 'prov_id' => '52' , 'name' => 'KOTA BIMA',]);
        Kota::create(['id' => 5301 , 'prov_id' => '53' , 'name' => 'KABUPATEN SUMBA BARAT',]);
        Kota::create(['id' => 5302 , 'prov_id' => '53' , 'name' => 'KABUPATEN SUMBA TIMUR',]);
        Kota::create(['id' => 5303 , 'prov_id' => '53' , 'name' => 'KABUPATEN KUPANG',]);
        Kota::create(['id' => 5304 , 'prov_id' => '53' , 'name' => 'KABUPATEN TIMOR TENGAH SELATAN',]);
        Kota::create(['id' => 5305 , 'prov_id' => '53' , 'name' => 'KABUPATEN TIMOR TENGAH UTARA',]);
        Kota::create(['id' => 5306 , 'prov_id' => '53' , 'name' => 'KABUPATEN BELU',]);
        Kota::create(['id' => 5307 , 'prov_id' => '53' , 'name' => 'KABUPATEN ALOR',]);
        Kota::create(['id' => 5308 , 'prov_id' => '53' , 'name' => 'KABUPATEN LEMBATA',]);
        Kota::create(['id' => 5309 , 'prov_id' => '53' , 'name' => 'KABUPATEN FLORES TIMUR',]);
        Kota::create(['id' => 5310 , 'prov_id' => '53' , 'name' => 'KABUPATEN SIKKA',]);
        Kota::create(['id' => 5311 , 'prov_id' => '53' , 'name' => 'KABUPATEN ENDE',]);
        Kota::create(['id' => 5312 , 'prov_id' => '53' , 'name' => 'KABUPATEN NGADA',]);
        Kota::create(['id' => 5313 , 'prov_id' => '53' , 'name' => 'KABUPATEN MANGGARAI',]);
        Kota::create(['id' => 5314 , 'prov_id' => '53' , 'name' => 'KABUPATEN ROTE NDAO',]);
        Kota::create(['id' => 5315 , 'prov_id' => '53' , 'name' => 'KABUPATEN MANGGARAI BARAT',]);
        Kota::create(['id' => 5316 , 'prov_id' => '53' , 'name' => 'KABUPATEN SUMBA TENGAH',]);
        Kota::create(['id' => 5317 , 'prov_id' => '53' , 'name' => 'KABUPATEN SUMBA BARAT DAYA',]);
        Kota::create(['id' => 5318 , 'prov_id' => '53' , 'name' => 'KABUPATEN NAGEKEO',]);
        Kota::create(['id' => 5319 , 'prov_id' => '53' , 'name' => 'KABUPATEN MANGGARAI TIMUR',]);
        Kota::create(['id' => 5320 , 'prov_id' => '53' , 'name' => 'KABUPATEN SABU RAIJUA',]);
        Kota::create(['id' => 5321 , 'prov_id' => '53' , 'name' => 'KABUPATEN MALAKA',]);
        Kota::create(['id' => 5371 , 'prov_id' => '53' , 'name' => 'KOTA KUPANG',]);
        Kota::create(['id' => 6101 , 'prov_id' => '61' , 'name' => 'KABUPATEN SAMBAS',]);
        Kota::create(['id' => 6102 , 'prov_id' => '61' , 'name' => 'KABUPATEN BENGKAYANG',]);
        Kota::create(['id' => 6103 , 'prov_id' => '61' , 'name' => 'KABUPATEN LANDAK',]);
        Kota::create(['id' => 6104 , 'prov_id' => '61' , 'name' => 'KABUPATEN MEMPAWAH',]);
        Kota::create(['id' => 6105 , 'prov_id' => '61' , 'name' => 'KABUPATEN SANGGAU',]);
        Kota::create(['id' => 6106 , 'prov_id' => '61' , 'name' => 'KABUPATEN KETAPANG',]);
        Kota::create(['id' => 6107 , 'prov_id' => '61' , 'name' => 'KABUPATEN SINTANG',]);
        Kota::create(['id' => 6108 , 'prov_id' => '61' , 'name' => 'KABUPATEN KAPUAS HULU',]);
        Kota::create(['id' => 6109 , 'prov_id' => '61' , 'name' => 'KABUPATEN SEKADAU',]);
        Kota::create(['id' => 6110 , 'prov_id' => '61' , 'name' => 'KABUPATEN MELAWI',]);
        Kota::create(['id' => 6111 , 'prov_id' => '61' , 'name' => 'KABUPATEN KAYONG UTARA',]);
        Kota::create(['id' => 6112 , 'prov_id' => '61' , 'name' => 'KABUPATEN KUBU RAYA',]);
        Kota::create(['id' => 6171 , 'prov_id' => '61' , 'name' => 'KOTA PONTIANAK',]);
        Kota::create(['id' => 6172 , 'prov_id' => '61' , 'name' => 'KOTA SINGKAWANG',]);
        Kota::create(['id' => 6201 , 'prov_id' => '62' , 'name' => 'KABUPATEN KOTAWARINGIN BARAT',]);
        Kota::create(['id' => 6202 , 'prov_id' => '62' , 'name' => 'KABUPATEN KOTAWARINGIN TIMUR',]);
        Kota::create(['id' => 6203 , 'prov_id' => '62' , 'name' => 'KABUPATEN KAPUAS',]);
        Kota::create(['id' => 6204 , 'prov_id' => '62' , 'name' => 'KABUPATEN BARITO SELATAN',]);
        Kota::create(['id' => 6205 , 'prov_id' => '62' , 'name' => 'KABUPATEN BARITO UTARA',]);
        Kota::create(['id' => 6206 , 'prov_id' => '62' , 'name' => 'KABUPATEN SUKAMARA',]);
        Kota::create(['id' => 6207 , 'prov_id' => '62' , 'name' => 'KABUPATEN LAMANDAU',]);
        Kota::create(['id' => 6208 , 'prov_id' => '62' , 'name' => 'KABUPATEN SERUYAN',]);
        Kota::create(['id' => 6209 , 'prov_id' => '62' , 'name' => 'KABUPATEN KATINGAN',]);
        Kota::create(['id' => 6210 , 'prov_id' => '62' , 'name' => 'KABUPATEN PULANG PISAU',]);
        Kota::create(['id' => 6211 , 'prov_id' => '62' , 'name' => 'KABUPATEN GUNUNG MAS',]);
        Kota::create(['id' => 6212 , 'prov_id' => '62' , 'name' => 'KABUPATEN BARITO TIMUR',]);
        Kota::create(['id' => 6213 , 'prov_id' => '62' , 'name' => 'KABUPATEN MURUNG RAYA',]);
        Kota::create(['id' => 6271 , 'prov_id' => '62' , 'name' => 'KOTA PALANGKA RAYA',]);
        Kota::create(['id' => 6301 , 'prov_id' => '63' , 'name' => 'KABUPATEN TANAH LAUT',]);
        Kota::create(['id' => 6302 , 'prov_id' => '63' , 'name' => 'KABUPATEN KOTA BARU',]);
        Kota::create(['id' => 6303 , 'prov_id' => '63' , 'name' => 'KABUPATEN BANJAR',]);
        Kota::create(['id' => 6304 , 'prov_id' => '63' , 'name' => 'KABUPATEN BARITO KUALA',]);
        Kota::create(['id' => 6305 , 'prov_id' => '63' , 'name' => 'KABUPATEN TAPIN',]);
        Kota::create(['id' => 6306 , 'prov_id' => '63' , 'name' => 'KABUPATEN HULU SUNGAI SELATAN',]);
        Kota::create(['id' => 6307 , 'prov_id' => '63' , 'name' => 'KABUPATEN HULU SUNGAI TENGAH',]);
        Kota::create(['id' => 6308 , 'prov_id' => '63' , 'name' => 'KABUPATEN HULU SUNGAI UTARA',]);
        Kota::create(['id' => 6309 , 'prov_id' => '63' , 'name' => 'KABUPATEN TABALONG',]);
        Kota::create(['id' => 6310 , 'prov_id' => '63' , 'name' => 'KABUPATEN TANAH BUMBU',]);
        Kota::create(['id' => 6311 , 'prov_id' => '63' , 'name' => 'KABUPATEN BALANGAN',]);
        Kota::create(['id' => 6371 , 'prov_id' => '63' , 'name' => 'KOTA BANJARMASIN',]);
        Kota::create(['id' => 6372 , 'prov_id' => '63' , 'name' => 'KOTA BANJAR BARU',]);
        Kota::create(['id' => 6401 , 'prov_id' => '64' , 'name' => 'KABUPATEN PASER',]);
        Kota::create(['id' => 6402 , 'prov_id' => '64' , 'name' => 'KABUPATEN KUTAI BARAT',]);
        Kota::create(['id' => 6403 , 'prov_id' => '64' , 'name' => 'KABUPATEN KUTAI KARTANEGARA',]);
        Kota::create(['id' => 6404 , 'prov_id' => '64' , 'name' => 'KABUPATEN KUTAI TIMUR',]);
        Kota::create(['id' => 6405 , 'prov_id' => '64' , 'name' => 'KABUPATEN BERAU',]);
        Kota::create(['id' => 6409 , 'prov_id' => '64' , 'name' => 'KABUPATEN PENAJAM PASER UTARA',]);
        Kota::create(['id' => 6411 , 'prov_id' => '64' , 'name' => 'KABUPATEN MAHAKAM HULU',]);
        Kota::create(['id' => 6471 , 'prov_id' => '64' , 'name' => 'KOTA BALIKPAPAN',]);
        Kota::create(['id' => 6472 , 'prov_id' => '64' , 'name' => 'KOTA SAMARINDA',]);
        Kota::create(['id' => 6474 , 'prov_id' => '64' , 'name' => 'KOTA BONTANG',]);
        Kota::create(['id' => 6501 , 'prov_id' => '65' , 'name' => 'KABUPATEN MALINAU',]);
        Kota::create(['id' => 6502 , 'prov_id' => '65' , 'name' => 'KABUPATEN BULUNGAN',]);
        Kota::create(['id' => 6503 , 'prov_id' => '65' , 'name' => 'KABUPATEN TANA TIDUNG',]);
        Kota::create(['id' => 6504 , 'prov_id' => '65' , 'name' => 'KABUPATEN NUNUKAN',]);
        Kota::create(['id' => 6571 , 'prov_id' => '65' , 'name' => 'KOTA TARAKAN',]);
        Kota::create(['id' => 7101 , 'prov_id' => '71' , 'name' => 'KABUPATEN BOLAANG MONGONDOW',]);
        Kota::create(['id' => 7102 , 'prov_id' => '71' , 'name' => 'KABUPATEN MINAHASA',]);
        Kota::create(['id' => 7103 , 'prov_id' => '71' , 'name' => 'KABUPATEN KEPULAUAN SANGIHE',]);
        Kota::create(['id' => 7104 , 'prov_id' => '71' , 'name' => 'KABUPATEN KEPULAUAN TALAUD',]);
        Kota::create(['id' => 7105 , 'prov_id' => '71' , 'name' => 'KABUPATEN MINAHASA SELATAN',]);
        Kota::create(['id' => 7106 , 'prov_id' => '71' , 'name' => 'KABUPATEN MINAHASA UTARA',]);
        Kota::create(['id' => 7107 , 'prov_id' => '71' , 'name' => 'KABUPATEN BOLAANG MONGONDOW UTARA',]);
        Kota::create(['id' => 7108 , 'prov_id' => '71' , 'name' => 'KABUPATEN SIAU TAGULANDANG BIARO',]);
        Kota::create(['id' => 7109 , 'prov_id' => '71' , 'name' => 'KABUPATEN MINAHASA TENGGARA',]);
        Kota::create(['id' => 7110 , 'prov_id' => '71' , 'name' => 'KABUPATEN BOLAANG MONGONDOW SELATAN',]);
        Kota::create(['id' => 7111 , 'prov_id' => '71' , 'name' => 'KABUPATEN BOLAANG MONGONDOW TIMUR',]);
        Kota::create(['id' => 7171 , 'prov_id' => '71' , 'name' => 'KOTA MANADO',]);
        Kota::create(['id' => 7172 , 'prov_id' => '71' , 'name' => 'KOTA BITUNG',]);
        Kota::create(['id' => 7173 , 'prov_id' => '71' , 'name' => 'KOTA TOMOHON',]);
        Kota::create(['id' => 7174 , 'prov_id' => '71' , 'name' => 'KOTA KOTAMOBAGU',]);
        Kota::create(['id' => 7201 , 'prov_id' => '72' , 'name' => 'KABUPATEN BANGGAI KEPULAUAN',]);
        Kota::create(['id' => 7202 , 'prov_id' => '72' , 'name' => 'KABUPATEN BANGGAI',]);
        Kota::create(['id' => 7203 , 'prov_id' => '72' , 'name' => 'KABUPATEN MOROWALI',]);
        Kota::create(['id' => 7204 , 'prov_id' => '72' , 'name' => 'KABUPATEN POSO',]);
        Kota::create(['id' => 7205 , 'prov_id' => '72' , 'name' => 'KABUPATEN DONGGALA',]);
        Kota::create(['id' => 7206 , 'prov_id' => '72' , 'name' => 'KABUPATEN TOLI-TOLI',]);
        Kota::create(['id' => 7207 , 'prov_id' => '72' , 'name' => 'KABUPATEN BUOL',]);
        Kota::create(['id' => 7208 , 'prov_id' => '72' , 'name' => 'KABUPATEN PARIGI MOUTONG',]);
        Kota::create(['id' => 7209 , 'prov_id' => '72' , 'name' => 'KABUPATEN TOJO UNA-UNA',]);
        Kota::create(['id' => 7210 , 'prov_id' => '72' , 'name' => 'KABUPATEN SIGI',]);
        Kota::create(['id' => 7211 , 'prov_id' => '72' , 'name' => 'KABUPATEN BANGGAI LAUT',]);
        Kota::create(['id' => 7212 , 'prov_id' => '72' , 'name' => 'KABUPATEN MOROWALI UTARA',]);
        Kota::create(['id' => 7271 , 'prov_id' => '72' , 'name' => 'KOTA PALU',]);
        Kota::create(['id' => 7301 , 'prov_id' => '73' , 'name' => 'KABUPATEN KEPULAUAN SELAYAR',]);
        Kota::create(['id' => 7302 , 'prov_id' => '73' , 'name' => 'KABUPATEN BULUKUMBA',]);
        Kota::create(['id' => 7303 , 'prov_id' => '73' , 'name' => 'KABUPATEN BANTAENG',]);
        Kota::create(['id' => 7304 , 'prov_id' => '73' , 'name' => 'KABUPATEN JENEPONTO',]);
        Kota::create(['id' => 7305 , 'prov_id' => '73' , 'name' => 'KABUPATEN TAKALAR',]);
        Kota::create(['id' => 7306 , 'prov_id' => '73' , 'name' => 'KABUPATEN GOWA',]);
        Kota::create(['id' => 7307 , 'prov_id' => '73' , 'name' => 'KABUPATEN SINJAI',]);
        Kota::create(['id' => 7308 , 'prov_id' => '73' , 'name' => 'KABUPATEN MAROS',]);
        Kota::create(['id' => 7309 , 'prov_id' => '73' , 'name' => 'KABUPATEN PANGKAJENE DAN KEPULAUAN',]);
        Kota::create(['id' => 7310 , 'prov_id' => '73' , 'name' => 'KABUPATEN BARRU',]);
        Kota::create(['id' => 7311 , 'prov_id' => '73' , 'name' => 'KABUPATEN BONE',]);
        Kota::create(['id' => 7312 , 'prov_id' => '73' , 'name' => 'KABUPATEN SOPPENG',]);
        Kota::create(['id' => 7313 , 'prov_id' => '73' , 'name' => 'KABUPATEN WAJO',]);
        Kota::create(['id' => 7314 , 'prov_id' => '73' , 'name' => 'KABUPATEN SIDENRENG RAPPANG',]);
        Kota::create(['id' => 7315 , 'prov_id' => '73' , 'name' => 'KABUPATEN PINRANG',]);
        Kota::create(['id' => 7316 , 'prov_id' => '73' , 'name' => 'KABUPATEN ENREKANG',]);
        Kota::create(['id' => 7317 , 'prov_id' => '73' , 'name' => 'KABUPATEN LUWU',]);
        Kota::create(['id' => 7318 , 'prov_id' => '73' , 'name' => 'KABUPATEN TANA TORAJA',]);
        Kota::create(['id' => 7322 , 'prov_id' => '73' , 'name' => 'KABUPATEN LUWU UTARA',]);
        Kota::create(['id' => 7325 , 'prov_id' => '73' , 'name' => 'KABUPATEN LUWU TIMUR',]);
        Kota::create(['id' => 7326 , 'prov_id' => '73' , 'name' => 'KABUPATEN TORAJA UTARA',]);
        Kota::create(['id' => 7371 , 'prov_id' => '73' , 'name' => 'KOTA MAKASSAR',]);
        Kota::create(['id' => 7372 , 'prov_id' => '73' , 'name' => 'KOTA PAREPARE',]);
        Kota::create(['id' => 7373 , 'prov_id' => '73' , 'name' => 'KOTA PALOPO',]);
        Kota::create(['id' => 7401 , 'prov_id' => '74' , 'name' => 'KABUPATEN BUTON',]);
        Kota::create(['id' => 7402 , 'prov_id' => '74' , 'name' => 'KABUPATEN MUNA',]);
        Kota::create(['id' => 7403 , 'prov_id' => '74' , 'name' => 'KABUPATEN KONAWE',]);
        Kota::create(['id' => 7404 , 'prov_id' => '74' , 'name' => 'KABUPATEN KOLAKA',]);
        Kota::create(['id' => 7405 , 'prov_id' => '74' , 'name' => 'KABUPATEN KONAWE SELATAN',]);
        Kota::create(['id' => 7406 , 'prov_id' => '74' , 'name' => 'KABUPATEN BOMBANA',]);
        Kota::create(['id' => 7407 , 'prov_id' => '74' , 'name' => 'KABUPATEN WAKATOBI',]);
        Kota::create(['id' => 7408 , 'prov_id' => '74' , 'name' => 'KABUPATEN KOLAKA UTARA',]);
        Kota::create(['id' => 7409 , 'prov_id' => '74' , 'name' => 'KABUPATEN BUTON UTARA',]);
        Kota::create(['id' => 7410 , 'prov_id' => '74' , 'name' => 'KABUPATEN KONAWE UTARA',]);
        Kota::create(['id' => 7411 , 'prov_id' => '74' , 'name' => 'KABUPATEN KOLAKA TIMUR',]);
        Kota::create(['id' => 7412 , 'prov_id' => '74' , 'name' => 'KABUPATEN KONAWE KEPULAUAN',]);
        Kota::create(['id' => 7413 , 'prov_id' => '74' , 'name' => 'KABUPATEN MUNA BARAT',]);
        Kota::create(['id' => 7414 , 'prov_id' => '74' , 'name' => 'KABUPATEN BUTON TENGAH',]);
        Kota::create(['id' => 7415 , 'prov_id' => '74' , 'name' => 'KABUPATEN BUTON SELATAN',]);
        Kota::create(['id' => 7471 , 'prov_id' => '74' , 'name' => 'KOTA KENDARI',]);
        Kota::create(['id' => 7472 , 'prov_id' => '74' , 'name' => 'KOTA BAUBAU',]);
        Kota::create(['id' => 7501 , 'prov_id' => '75' , 'name' => 'KABUPATEN BOALEMO',]);
        Kota::create(['id' => 7502 , 'prov_id' => '75' , 'name' => 'KABUPATEN GORONTALO',]);
        Kota::create(['id' => 7503 , 'prov_id' => '75' , 'name' => 'KABUPATEN POHUWATO',]);
        Kota::create(['id' => 7504 , 'prov_id' => '75' , 'name' => 'KABUPATEN BONE BOLANGO',]);
        Kota::create(['id' => 7505 , 'prov_id' => '75' , 'name' => 'KABUPATEN GORONTALO UTARA',]);
        Kota::create(['id' => 7571 , 'prov_id' => '75' , 'name' => 'KOTA GORONTALO',]);
        Kota::create(['id' => 7601 , 'prov_id' => '76' , 'name' => 'KABUPATEN MAJENE',]);
        Kota::create(['id' => 7602 , 'prov_id' => '76' , 'name' => 'KABUPATEN POLEWALI MANDAR',]);
        Kota::create(['id' => 7603 , 'prov_id' => '76' , 'name' => 'KABUPATEN MAMASA',]);
        Kota::create(['id' => 7604 , 'prov_id' => '76' , 'name' => 'KABUPATEN MAMUJU',]);
        Kota::create(['id' => 7605 , 'prov_id' => '76' , 'name' => 'KABUPATEN MAMUJU UTARA',]);
        Kota::create(['id' => 7606 , 'prov_id' => '76' , 'name' => 'KABUPATEN MAMUJU TENGAH',]);
        Kota::create(['id' => 8101 , 'prov_id' => '81' , 'name' => 'KABUPATEN MALUKU TENGGARA BARAT',]);
        Kota::create(['id' => 8102 , 'prov_id' => '81' , 'name' => 'KABUPATEN MALUKU TENGGARA',]);
        Kota::create(['id' => 8103 , 'prov_id' => '81' , 'name' => 'KABUPATEN MALUKU TENGAH',]);
        Kota::create(['id' => 8104 , 'prov_id' => '81' , 'name' => 'KABUPATEN BURU',]);
        Kota::create(['id' => 8105 , 'prov_id' => '81' , 'name' => 'KABUPATEN KEPULAUAN ARU',]);
        Kota::create(['id' => 8106 , 'prov_id' => '81' , 'name' => 'KABUPATEN SERAM BAGIAN BARAT',]);
        Kota::create(['id' => 8107 , 'prov_id' => '81' , 'name' => 'KABUPATEN SERAM BAGIAN TIMUR',]);
        Kota::create(['id' => 8108 , 'prov_id' => '81' , 'name' => 'KABUPATEN MALUKU BARAT DAYA',]);
        Kota::create(['id' => 8109 , 'prov_id' => '81' , 'name' => 'KABUPATEN BURU SELATAN',]);
        Kota::create(['id' => 8171 , 'prov_id' => '81' , 'name' => 'KOTA AMBON',]);
        Kota::create(['id' => 8172 , 'prov_id' => '81' , 'name' => 'KOTA TUAL',]);
        Kota::create(['id' => 8201 , 'prov_id' => '82' , 'name' => 'KABUPATEN HALMAHERA BARAT',]);
        Kota::create(['id' => 8202 , 'prov_id' => '82' , 'name' => 'KABUPATEN HALMAHERA TENGAH',]);
        Kota::create(['id' => 8203 , 'prov_id' => '82' , 'name' => 'KABUPATEN KEPULAUAN SULA',]);
        Kota::create(['id' => 8204 , 'prov_id' => '82' , 'name' => 'KABUPATEN HALMAHERA SELATAN',]);
        Kota::create(['id' => 8205 , 'prov_id' => '82' , 'name' => 'KABUPATEN HALMAHERA UTARA',]);
        Kota::create(['id' => 8206 , 'prov_id' => '82' , 'name' => 'KABUPATEN HALMAHERA TIMUR',]);
        Kota::create(['id' => 8207 , 'prov_id' => '82' , 'name' => 'KABUPATEN PULAU MOROTAI',]);
        Kota::create(['id' => 8208 , 'prov_id' => '82' , 'name' => 'KABUPATEN PULAU TALIABU',]);
        Kota::create(['id' => 8271 , 'prov_id' => '82' , 'name' => 'KOTA TERNATE',]);
        Kota::create(['id' => 8272 , 'prov_id' => '82' , 'name' => 'KOTA TIDORE KEPULAUAN',]);
        Kota::create(['id' => 9101 , 'prov_id' => '91' , 'name' => 'KABUPATEN FAKFAK',]);
        Kota::create(['id' => 9102 , 'prov_id' => '91' , 'name' => 'KABUPATEN KAIMANA',]);
        Kota::create(['id' => 9103 , 'prov_id' => '91' , 'name' => 'KABUPATEN TELUK WONDAMA',]);
        Kota::create(['id' => 9104 , 'prov_id' => '91' , 'name' => 'KABUPATEN TELUK BINTUNI',]);
        Kota::create(['id' => 9105 , 'prov_id' => '91' , 'name' => 'KABUPATEN MANOKWARI',]);
        Kota::create(['id' => 9106 , 'prov_id' => '91' , 'name' => 'KABUPATEN SORONG SELATAN',]);
        Kota::create(['id' => 9107 , 'prov_id' => '91' , 'name' => 'KABUPATEN SORONG',]);
        Kota::create(['id' => 9108 , 'prov_id' => '91' , 'name' => 'KABUPATEN RAJA AMPAT',]);
        Kota::create(['id' => 9109 , 'prov_id' => '91' , 'name' => 'KABUPATEN TAMBRAUW',]);
        Kota::create(['id' => 9110 , 'prov_id' => '91' , 'name' => 'KABUPATEN MAYBRAT',]);
        Kota::create(['id' => 9111 , 'prov_id' => '91' , 'name' => 'KABUPATEN MANOKWARI SELATAN',]);
        Kota::create(['id' => 9112 , 'prov_id' => '91' , 'name' => 'KABUPATEN PEGUNUNGAN ARFAK',]);
        Kota::create(['id' => 9171 , 'prov_id' => '91' , 'name' => 'KOTA SORONG',]);
        Kota::create(['id' => 9401 , 'prov_id' => '94' , 'name' => 'KABUPATEN MERAUKE',]);
        Kota::create(['id' => 9402 , 'prov_id' => '94' , 'name' => 'KABUPATEN JAYAWIJAYA',]);
        Kota::create(['id' => 9403 , 'prov_id' => '94' , 'name' => 'KABUPATEN JAYAPURA',]);
        Kota::create(['id' => 9404 , 'prov_id' => '94' , 'name' => 'KABUPATEN NABIRE',]);
        Kota::create(['id' => 9408 , 'prov_id' => '94' , 'name' => 'KABUPATEN KEPULAUAN YAPEN',]);
        Kota::create(['id' => 9409 , 'prov_id' => '94' , 'name' => 'KABUPATEN BIAK NUMFOR',]);
        Kota::create(['id' => 9410 , 'prov_id' => '94' , 'name' => 'KABUPATEN PANIAI',]);
        Kota::create(['id' => 9411 , 'prov_id' => '94' , 'name' => 'KABUPATEN PUNCAK JAYA',]);
        Kota::create(['id' => 9412 , 'prov_id' => '94' , 'name' => 'KABUPATEN MIMIKA',]);
        Kota::create(['id' => 9413 , 'prov_id' => '94' , 'name' => 'KABUPATEN BOVEN DIGOEL',]);
        Kota::create(['id' => 9414 , 'prov_id' => '94' , 'name' => 'KABUPATEN MAPPI',]);
        Kota::create(['id' => 9415 , 'prov_id' => '94' , 'name' => 'KABUPATEN ASMAT',]);
        Kota::create(['id' => 9416 , 'prov_id' => '94' , 'name' => 'KABUPATEN YAHUKIMO',]);
        Kota::create(['id' => 9417 , 'prov_id' => '94' , 'name' => 'KABUPATEN PEGUNUNGAN BINTANG',]);
        Kota::create(['id' => 9418 , 'prov_id' => '94' , 'name' => 'KABUPATEN TOLIKARA',]);
        Kota::create(['id' => 9419 , 'prov_id' => '94' , 'name' => 'KABUPATEN SARMI',]);
        Kota::create(['id' => 9420 , 'prov_id' => '94' , 'name' => 'KABUPATEN KEEROM',]);
        Kota::create(['id' => 9426 , 'prov_id' => '94' , 'name' => 'KABUPATEN WAROPEN',]);
        Kota::create(['id' => 9427 , 'prov_id' => '94' , 'name' => 'KABUPATEN SUPIORI',]);
        Kota::create(['id' => 9428 , 'prov_id' => '94' , 'name' => 'KABUPATEN MAMBERAMO RAYA',]);
        Kota::create(['id' => 9429 , 'prov_id' => '94' , 'name' => 'KABUPATEN NDUGA',]);
        Kota::create(['id' => 9430 , 'prov_id' => '94' , 'name' => 'KABUPATEN LANNY JAYA',]);
        Kota::create(['id' => 9431 , 'prov_id' => '94' , 'name' => 'KABUPATEN MAMBERAMO TENGAH',]);
        Kota::create(['id' => 9432 , 'prov_id' => '94' , 'name' => 'KABUPATEN YALIMO',]);
        Kota::create(['id' => 9433 , 'prov_id' => '94' , 'name' => 'KABUPATEN PUNCAK',]);
        Kota::create(['id' => 9434 , 'prov_id' => '94' , 'name' => 'KABUPATEN DOGIYAI',]);
        Kota::create(['id' => 9435 , 'prov_id' => '94' , 'name' => 'KABUPATEN INTAN JAYA',]);
        Kota::create(['id' => 9436 , 'prov_id' => '94' , 'name' => 'KABUPATEN DEIYAI',]);
        Kota::create(['id' => 9471 , 'prov_id' => '94' , 'name' => 'KOTA JAYAPURA',]);

    }
}
